"""Add device_count fields

Revision ID: 5e3d8f7a1c2b
Revises: c91059d29a6a
Create Date: 2026-05-26 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e3d8f7a1c2b'
down_revision = 'c91059d29a6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_enforcement', sa.Column('device_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('checkpoint', sa.Column('device_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkpoint', 'device_count')
    op.drop_column('parking_enforcement', 'device_count')
    # ### end Alembic commands ###
