"""initial schema from current models

Revision ID: 6f1aa5fb462e
Revises: 
Create Date: 2026-05-28 22:24:41.441648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f1aa5fb462e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backend_device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('point_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('server_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('storage_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('switch_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('firewall_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fiber_converter_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('power_supply_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cabinet_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('other_device_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('port', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('power_source', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('network_source', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'point', ['point_id'], ['id'])

    with op.batch_alter_table('checkpoint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkpoint_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('extended_warranty_expire_date', sa.Date(), nullable=True))
        batch_op.drop_column('device_count')

    with op.batch_alter_table('electronic_police', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extended_warranty_expire_date', sa.Date(), nullable=True))

    with op.batch_alter_table('intersection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('east_west_road', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('north_south_road', sa.String(length=100), nullable=True))

    with op.batch_alter_table('parking_enforcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera_area', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('extended_warranty_expire_date', sa.Date(), nullable=True))
        batch_op.drop_column('device_count')

    with op.batch_alter_table('traffic_light', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extended_warranty_expire_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic_light', schema=None) as batch_op:
        batch_op.drop_column('extended_warranty_expire_date')

    with op.batch_alter_table('parking_enforcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_count', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.drop_column('extended_warranty_expire_date')
        batch_op.drop_column('camera_area')

    with op.batch_alter_table('intersection', schema=None) as batch_op:
        batch_op.drop_column('north_south_road')
        batch_op.drop_column('east_west_road')

    with op.batch_alter_table('electronic_police', schema=None) as batch_op:
        batch_op.drop_column('extended_warranty_expire_date')

    with op.batch_alter_table('checkpoint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_count', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.drop_column('extended_warranty_expire_date')
        batch_op.drop_column('checkpoint_type')

    with op.batch_alter_table('backend_device', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('network_source')
        batch_op.drop_column('power_source')
        batch_op.drop_column('location')
        batch_op.drop_column('port')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('other_device_count')
        batch_op.drop_column('cabinet_count')
        batch_op.drop_column('power_supply_count')
        batch_op.drop_column('fiber_converter_count')
        batch_op.drop_column('firewall_count')
        batch_op.drop_column('switch_count')
        batch_op.drop_column('storage_count')
        batch_op.drop_column('server_count')
        batch_op.drop_column('point_id')

    # ### end Alembic commands ###
