"""add countdown_timer_count column to traffic_light table

Revision ID: add_countdown_timer_count
Revises: fd5245c15e8f
Create Date: 2026-06-03 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'add_countdown_timer_count'
down_revision = 'fd5245c15e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic_light', schema=None) as batch_op:
        batch_op.add_column(sa.Column('countdown_timer_count', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic_light', schema=None) as batch_op:
        batch_op.drop_column('countdown_timer_count')

    # ### end Alembic commands ###