"""add model and quantity columns to backend_device table

Revision ID: add_backend_device_model_quantity
Revises: add_countdown_timer_count
Create Date: 2026-06-04 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'add_backend_device_model_quantity'
down_revision = 'add_countdown_timer_count'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backend_device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.String(length=100), nullable=True, comment='设备品牌型号'))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False, server_default='1', comment='设备数量'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backend_device', schema=None) as batch_op:
        batch_op.drop_column('quantity')
        batch_op.drop_column('model')

    # ### end Alembic commands ###
