"""add selected_traffic_light_id to intersection table

Revision ID: add_selected_traffic_light_id
Revises: add_backend_device_model_quantity
Create Date: 2026-06-12 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_selected_traffic_light_id'
down_revision = 'add_backend_device_model_quantity'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intersection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_traffic_light_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_intersection_selected_traffic_light', 'traffic_light', ['selected_traffic_light_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intersection', schema=None) as batch_op:
        batch_op.drop_constraint('fk_intersection_selected_traffic_light', type_='foreignkey')
        batch_op.drop_column('selected_traffic_light_id')

    # ### end Alembic commands ###