"""Initial migration

Revision ID: c91059d29a6a
Revises: 
Create Date: 2026-05-25 21:28:32.126884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91059d29a6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('related_entity_type', sa.String(length=50), nullable=False),
    sa.Column('related_entity_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('upload_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('uploaded_by', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intersection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('十字路口', '丁字路口', '行人过街', '其他', name='intersection_type'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contract_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('acceptance_date', sa.Date(), nullable=True),
    sa.Column('warranty_period', sa.String(length=50), nullable=True),
    sa.Column('warranty_expire_date', sa.Date(), nullable=False),
    sa.Column('builder', sa.String(length=100), nullable=True),
    sa.Column('constructor', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('admin', 'editor', 'viewer', name='user_role'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('backend_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('camera_count', sa.Integer(), nullable=False),
    sa.Column('strobe_light_count', sa.Integer(), nullable=False),
    sa.Column('radar_count', sa.Integer(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('power_source', sa.Text(), nullable=True),
    sa.Column('network_source', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['point_id'], ['point.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electronic_police',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intersection_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('capture_type', sa.String(length=50), nullable=True),
    sa.Column('terminal_server_count', sa.Integer(), nullable=False),
    sa.Column('forward_capture_count', sa.Integer(), nullable=False),
    sa.Column('reverse_capture_count', sa.Integer(), nullable=False),
    sa.Column('led_light_count', sa.Integer(), nullable=False),
    sa.Column('strobe_light_count', sa.Integer(), nullable=False),
    sa.Column('ptz_count', sa.Integer(), nullable=False),
    sa.Column('signal_detector_count', sa.Integer(), nullable=False),
    sa.Column('network_source', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersection.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('operation_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parking_enforcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('camera_count', sa.Integer(), nullable=False),
    sa.Column('parking_sign_count', sa.Integer(), nullable=False),
    sa.Column('monitor_sign_count', sa.Integer(), nullable=False),
    sa.Column('power_source', sa.Text(), nullable=True),
    sa.Column('network_source', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['point_id'], ['point.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traffic_light',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intersection_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=True),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.Column('left_arrow_count', sa.Integer(), nullable=False),
    sa.Column('straight_arrow_count', sa.Integer(), nullable=False),
    sa.Column('right_arrow_count', sa.Integer(), nullable=False),
    sa.Column('full_screen_count', sa.Integer(), nullable=False),
    sa.Column('non_motor_count', sa.Integer(), nullable=False),
    sa.Column('pedestrian_count', sa.Integer(), nullable=False),
    sa.Column('radar_count', sa.Integer(), nullable=False),
    sa.Column('guide_screen_count', sa.Integer(), nullable=False),
    sa.Column('power_source', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersection.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warranty_extension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_type', sa.String(length=50), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('extension_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warranty_extension')
    op.drop_table('traffic_light')
    op.drop_table('parking_enforcement')
    op.drop_table('operation_log')
    op.drop_table('electronic_police')
    op.drop_table('checkpoint')
    op.drop_table('backend_device')
    op.drop_table('user')
    op.drop_table('project')
    op.drop_table('point')
    op.drop_table('intersection')
    op.drop_table('attachment')
    # ### end Alembic commands ###
