"""add maintenance_record table

Revision ID: fd5245c15e8f
Revises: 6f1aa5fb462e
Create Date: 2026-05-31 21:35:51.099193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd5245c15e8f'
down_revision = '6f1aa5fb462e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_type', sa.String(length=50), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('fault_level', sa.String(length=20), nullable=False),
    sa.Column('fault_description', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('record_time', sa.DateTime(), nullable=False),
    sa.Column('recorder_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recorder_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('operation_log')
    with op.batch_alter_table('backend_device', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])

    with op.batch_alter_table('checkpoint', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cp_point'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'checkpoint_point', ['point_id'], ['id'])

    with op.batch_alter_table('parking_enforcement', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_pe_point'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'parking_enforcement_point', ['point_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_enforcement', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_pe_point'), 'parking_enforcement_point', ['point_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('checkpoint', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_cp_point'), 'checkpoint_point', ['point_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('backend_device', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('operation_log',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('operation_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('entity_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('entity_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('old_value', mysql.TEXT(), nullable=True),
    sa.Column('new_value', mysql.TEXT(), nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('operation_time', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('operation_log_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('maintenance_record')
    # ### end Alembic commands ###
